name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-and-gtest:
    needs: clang-format
    runs-on: windows-2022
    if: github.actor == github.repository_owner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: Jimver/cuda-toolkit@v0.2.14
      id: cuda-toolkit
      with:
        cuda: "11.8.0"
        method: "network"

    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe
