name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  clang-format:
    runs-on: windows-2022
    if: github.actor == github.repository_owner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Install llvm
      run: choco install llvm

    - name: Execute clang-format
      run: |
        Get-ChildItem src -Recurse -Include *.cpp, *.hpp, *.h, *.cu | ForEach { clang-format -style=file -i $_.FullName }

    - name: Check Changes
      run: |
        if git status --porcelain; then
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Commit and Push
      if: env.CHANGED == 'true'
      run: |
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
        git add src
        git commit -m "Apply clang-format changes"
        git push origin ${{ github.head_ref }}
