name: Gtest
on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"
    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe
