name: Gtest
on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: Jimver/cuda-toolkit@v0.2.14
      id: cuda-toolkit
      with:
        cuda: "11.8.0"

    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe
