name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: 
      - 'src/*'
      - '.clang-format'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    if: github.actor != 'clang-format-bot'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Execute clang-format
      run: |
        find src -regex '.*\.\(cpp\|hpp\|h\|cu\)' -exec clang-format -style=file -i {} +

    - name: Commit and Push
      uses: EndBug/add-and-commit@v9
      with:
        author_name: clang-format-bot
        author_email: 26509537+chatflip@users.noreply.github.com
        message: "[CI] Apply clang-format changes"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-gtest:
    needs: clang-format
    runs-on: windows-2022
    if: github.actor != 'clang-format-bot'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: Jimver/cuda-toolkit@v0.2.14
      id: cuda-toolkit
      with:
        cuda: "11.8.0"
        method: "network"

    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe
