name: Gtest
on: [pull_request]

jobs:
  format:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      name: Checkout code
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install llvm
      run: choco install llvm

    - name: Execute clang-format
      run: |
        Get-ChildItem src -Recurse -Include *.cpp, *.hpp, *.h, *.cu | ForEach { clang-format -style=file -i $_.FullName }


    - name: Check Changes
      id: changes
      run: |
        if (git status --porcelain) {
          echo "::set-output name=changed::true"
        }

    - name: Commit and Push
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --global user.email "oo.chat.flip@gmail.com"
        git config --global user.name "chatflip"
        git add -A
        git commit -m "Apply clang-format changes"
        git push origin HEAD

  build-and-gtest:
    needs: format
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: Jimver/cuda-toolkit@v0.2.14
      id: cuda-toolkit
      with:
        cuda: "11.8.0"
        method: "network"

    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe
