name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: 
      - 'src/*'
      - '.clang-format'
      - '.github/workflows/*'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Execute clang-format
      run: |
        find src -regex '.*\.\(h\|cpp\|hpp\|cu\|cuh\)' -exec clang-format -style=file -i {} +
    - name: Check for Changes
      run: git diff --exit-code

  build-and-gtest:
    needs: clang-format
    runs-on: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: "11.8.0"
        method: "network"
        use-github-cache: "false"
        use-local-cache: "false"

    - name: Build project
      run: msbuild Gasyori100knockCUDA.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run Google Test
      run: ./bin/x64/Release/Gasyori100knockCUDA.exe --gtest_filter=ImageProcessingTest.Question_*_CPU